server:
  port: ${PORT:8080}
spring:
  profiles:
   active: ${PROFILE:}
credential:
  vk:
    confirmation-code: ${VK_CONFIRMATION_CODE}
    group-id: ${VK_GROUP_ID:}
    key: ${VK_KEY:}
  youtube:
    key: ${YOUTUBE_API_KEY:}
search:
  youtube:
    maxresults: ${MAX_RESULTS:10}